export const productAction = {
    FETCH_PRODUCT_REQUEST:"FETCH_PRODUCT_REQUEST",
    FETCH_PRODUCT_SUCCESS:"FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE:"FETCH_PRODUCT_FAILURE",
    FETCH_DEAL_OF_DAY_PRODUCT_SUCCESS: "FETCH_DEAL_OF_DAY_PRODUCT_SUCCESS",
    FETCH_FEATURE_PRODUCT_SUCCESS: "FETCH_FEATURE_PRODUCT_SUCCESS",
    FETCH_NEW_FOR_U_PRODUCT_SUCCESS: "FETCH_NEW_FOR_U_PRODUCT_SUCCESS",
    FETCH_BRAND1_PRODUCT_SUCCESS: "FETCH_BRAND1_PRODUCT_SUCCESS",
    FETCH_BRAND2_PRODUCT_SUCCESS: "FETCH_BRAND2_PRODUCT_SUCCESS",
    FETCH_BRAND3_PRODUCT_SUCCESS: "FETCH_BRAND3_PRODUCT_SUCCESS",
    FETCH_BRAND4_PRODUCT_SUCCESS: "FETCH_BRAND4_PRODUCT_SUCCESS",
}